/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BatchController;
import controller.SupplierController;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Batch;
import model.Supplier;

/**
 *
 * @author kasun
 */
public class AddBatchForm extends javax.swing.JFrame {
    private SupplierController supplierController;
    private BatchController controller;
    /**
     * Creates new form AddBatchForm
     */
    public AddBatchForm() {
        supplierController=new SupplierController();
        controller=new BatchController();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1097,794);
        loadTable();
        Date date = new Date();
        String strDateFormat = "hh:mm:ss a";
        DateFormat dateFormat = new SimpleDateFormat(strDateFormat);
        String formattedDate= dateFormat.format(date);

        txtDate.setText(formattedDate);
        
        
    }
    
    private void loadTable(){
        try {
            DefaultTableModel dtm=(DefaultTableModel) tblSupplier.getModel();
            List<Supplier> all = supplierController.getAll();
            for (Supplier supplier : all) {
                Object [] row={supplier.getS_id(),supplier.getName(),supplier.getMobile().get(0)};
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddBatchForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        sepFour = new javax.swing.JSeparator();
        lblDate = new javax.swing.JLabel();
        lblSupplierID = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        txtSupplierName = new javax.swing.JTextField();
        sepFour3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(153, 0, 153));
        pnlBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add New Batch");
        pnlBase.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 410, 110));

        txtDate.setBackground(new java.awt.Color(153, 0, 153));
        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setToolTipText("");
        txtDate.setBorder(null);
        txtDate.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtDate.setEnabled(false);
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
        });
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        pnlBase.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 320, 30));
        pnlBase.add(sepFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 320, 10));

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");
        pnlBase.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 230, 80));

        lblSupplierID.setBackground(new java.awt.Color(255, 255, 255));
        lblSupplierID.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblSupplierID.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplierID.setText("Supplier Name");
        pnlBase.add(lblSupplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 230, 80));

        btnSubmit.setBackground(new java.awt.Color(0, 0, 102));
        btnSubmit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnlBase.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 660, 120, 50));

        tblSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblSupplier.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Id", "Name", "mobile"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        pnlBase.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 910, 210));

        txtSupplierName.setBackground(new java.awt.Color(153, 0, 153));
        txtSupplierName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtSupplierName.setForeground(new java.awt.Color(255, 255, 255));
        txtSupplierName.setToolTipText("");
        txtSupplierName.setBorder(null);
        txtSupplierName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtSupplierName.setEnabled(false);
        txtSupplierName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSupplierNameFocusGained(evt);
            }
        });
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });
        pnlBase.add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 320, 30));
        pnlBase.add(sepFour3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 320, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        txtDate.setText("");
        //        if(!flag)
        //        txtMobile.setText("");
        //        flag=false;
    }//GEN-LAST:event_txtDateFocusGained

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(tblSupplier.getSelectedRow()==0){
            JOptionPane.showMessageDialog(this,"warning","select a table row",JOptionPane.WARNING_MESSAGE);
        }else if(tblSupplier.getSelectedRow()>1){
            JOptionPane.showMessageDialog(this,"warning","select only one table row",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                
                DefaultTableModel dtm= (DefaultTableModel) tblSupplier.getModel();
                int id = (int) dtm.getValueAt(tblSupplier.getSelectedRow(), 0);
                
                controller.addBatch(txtSupplierName.getText(), new Batch(0,id ,timestamp));
            } catch (SQLException ex) {
                Logger.getLogger(AddBatchForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtSupplierNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSupplierNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameFocusGained

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        DefaultTableModel dtm= (DefaultTableModel) tblSupplier.getModel();
        String  name= (String) dtm.getValueAt(tblSupplier.getSelectedRow(), 1);
        txtSupplierName.setText(name);
        
        
    }//GEN-LAST:event_tblSupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBatchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JSeparator sepFour;
    private javax.swing.JSeparator sepFour3;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
}
