/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Font.FontLoader;
import controller.CategoryController;
import controller.ItemController;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Item;
/**
 *
 * @author Benura
 */
public class AddItemForm extends javax.swing.JFrame {
  private ItemController controller=null;
  private CategoryController category=null;
  private boolean isLoaded=false;
  private int batch_id=0;
  private boolean isAvailable=false;
    /**
     * Creates new form AddItemForm
     */
    public AddItemForm() {
        initComponents();
        controller=new ItemController();
        category=new CategoryController();
//        Integer.parseInt("4792024007047");
        System.out.println(Long.MAX_VALUE);
                description.setFont(FontLoader.loadFont(24, Font.PLAIN));

        this.setLocationRelativeTo(null);
//        this.setSize(1366,696);
    }
    
    public AddItemForm(int id){
        controller=new ItemController();
        category=new CategoryController();
        this.batch_id=id;
        System.out.println("ko");
        initComponents();
        this.setLocationRelativeTo(null);
//        this.setSize(1366,696);
        isLoaded=true;
    }
    public void setBatchId(int id){
        itemBatchId.setText(""+id);
    }
    public void setCategoryId(String name){
        itemCategoryName.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        itemCategoryName = new javax.swing.JTextField();
        sepFour1 = new javax.swing.JSeparator();
        sepFour2 = new javax.swing.JSeparator();
        itemBatchId = new javax.swing.JTextField();
        sepFour3 = new javax.swing.JSeparator();
        thogaPrice = new javax.swing.JTextField();
        sepFour4 = new javax.swing.JSeparator();
        itemQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        itemTakingPrice = new javax.swing.JTextField();
        sepFour7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        itemId = new javax.swing.JTextField();
        sepFour8 = new javax.swing.JSeparator();
        select_batchId = new javax.swing.JButton();
        ourPrice = new javax.swing.JTextField();
        sepFour6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        sepFour9 = new javax.swing.JSeparator();
        txtShowPrice = new javax.swing.JTextField();
        select_batchId1 = new javax.swing.JButton();
        sepFour10 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        warningLevel = new javax.swing.JTextField();
        enter_btn = new javax.swing.JButton();
        sepFour5 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Items");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 360, 80));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Batch ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thoga Price");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Our Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 200, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Show Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 160, 40));

        itemCategoryName.setBackground(new java.awt.Color(153, 0, 153));
        itemCategoryName.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        itemCategoryName.setForeground(new java.awt.Color(255, 255, 255));
        itemCategoryName.setText("Enter Category Id Here");
        itemCategoryName.setToolTipText("");
        itemCategoryName.setBorder(null);
        itemCategoryName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        itemCategoryName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemCategoryNameFocusGained(evt);
            }
        });
        itemCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoryNameActionPerformed(evt);
            }
        });
        jPanel1.add(itemCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 320, 30));
        jPanel1.add(sepFour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 320, 0));
        jPanel1.add(sepFour2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, 320, 10));

        itemBatchId.setBackground(new java.awt.Color(153, 0, 153));
        itemBatchId.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        itemBatchId.setForeground(new java.awt.Color(255, 255, 255));
        itemBatchId.setText("Enter Batch ID Here");
        itemBatchId.setToolTipText("");
        itemBatchId.setBorder(null);
        itemBatchId.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        itemBatchId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemBatchIdFocusGained(evt);
            }
        });
        itemBatchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBatchIdActionPerformed(evt);
            }
        });
        jPanel1.add(itemBatchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 240, 30));
        jPanel1.add(sepFour3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 290, 10));

        thogaPrice.setBackground(new java.awt.Color(153, 0, 153));
        thogaPrice.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        thogaPrice.setForeground(new java.awt.Color(255, 255, 255));
        thogaPrice.setText("Enter Thoga Price Here");
        thogaPrice.setToolTipText("");
        thogaPrice.setBorder(null);
        thogaPrice.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        thogaPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                thogaPriceFocusGained(evt);
            }
        });
        thogaPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thogaPriceActionPerformed(evt);
            }
        });
        jPanel1.add(thogaPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 310, 30));
        jPanel1.add(sepFour4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 320, 10));

        itemQuantity.setBackground(new java.awt.Color(153, 0, 153));
        itemQuantity.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        itemQuantity.setForeground(new java.awt.Color(255, 255, 255));
        itemQuantity.setText("Enter Quantity Here");
        itemQuantity.setToolTipText("");
        itemQuantity.setBorder(null);
        itemQuantity.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        itemQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemQuantityFocusGained(evt);
            }
        });
        itemQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuantityActionPerformed(evt);
            }
        });
        jPanel1.add(itemQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 310, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Item ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 40));

        itemTakingPrice.setBackground(new java.awt.Color(153, 0, 153));
        itemTakingPrice.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        itemTakingPrice.setForeground(new java.awt.Color(255, 255, 255));
        itemTakingPrice.setText("Enter Taking Price Here");
        itemTakingPrice.setToolTipText("");
        itemTakingPrice.setBorder(null);
        itemTakingPrice.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        itemTakingPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemTakingPriceFocusGained(evt);
            }
        });
        itemTakingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTakingPriceActionPerformed(evt);
            }
        });
        jPanel1.add(itemTakingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 310, 30));
        jPanel1.add(sepFour7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 300, 10));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Category Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 210, 40));

        itemId.setBackground(new java.awt.Color(153, 0, 153));
        itemId.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        itemId.setForeground(new java.awt.Color(255, 255, 255));
        itemId.setText("Enter Id Here");
        itemId.setToolTipText("");
        itemId.setBorder(null);
        itemId.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        itemId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemIdFocusGained(evt);
            }
        });
        itemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdActionPerformed(evt);
            }
        });
        jPanel1.add(itemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 310, 30));
        jPanel1.add(sepFour8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 320, 10));

        select_batchId.setBackground(new java.awt.Color(0, 0, 255));
        select_batchId.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        select_batchId.setText("Choose");
        select_batchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_batchIdActionPerformed(evt);
            }
        });
        jPanel1.add(select_batchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 130, 40));

        ourPrice.setBackground(new java.awt.Color(153, 0, 153));
        ourPrice.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ourPrice.setForeground(new java.awt.Color(255, 255, 255));
        ourPrice.setText("Enter Our Price Here");
        ourPrice.setToolTipText("");
        ourPrice.setBorder(null);
        ourPrice.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        ourPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ourPriceFocusGained(evt);
            }
        });
        ourPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourPriceActionPerformed(evt);
            }
        });
        jPanel1.add(ourPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 290, 30));
        jPanel1.add(sepFour6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 300, 10));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Taking Price");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 160, 40));
        jPanel1.add(sepFour9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 320, 10));

        txtShowPrice.setBackground(new java.awt.Color(153, 0, 153));
        txtShowPrice.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtShowPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtShowPrice.setText("Enter Show Price Here");
        txtShowPrice.setToolTipText("");
        txtShowPrice.setBorder(null);
        txtShowPrice.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtShowPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtShowPriceFocusGained(evt);
            }
        });
        txtShowPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtShowPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 310, 30));

        select_batchId1.setBackground(new java.awt.Color(0, 0, 255));
        select_batchId1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        select_batchId1.setText("Choose");
        select_batchId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_batchId1ActionPerformed(evt);
            }
        });
        jPanel1.add(select_batchId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 130, 40));
        jPanel1.add(sepFour10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 320, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 696));

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 40));

        description.setBackground(new java.awt.Color(204, 0, 204));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 290, 150));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Warning Level");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 50));

        warningLevel.setBackground(new java.awt.Color(204, 0, 204));
        warningLevel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        warningLevel.setForeground(new java.awt.Color(255, 255, 255));
        warningLevel.setText("Warning Level");
        warningLevel.setToolTipText("");
        warningLevel.setBorder(null);
        warningLevel.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        warningLevel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                warningLevelFocusGained(evt);
            }
        });
        warningLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningLevelActionPerformed(evt);
            }
        });
        jPanel2.add(warningLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 300, 30));

        enter_btn.setBackground(new java.awt.Color(0, 0, 255));
        enter_btn.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        enter_btn.setText("Submit");
        enter_btn.setBorder(null);
        enter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_btnActionPerformed(evt);
            }
        });
        jPanel2.add(enter_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 110, 50));
        jPanel2.add(sepFour5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 210, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 560, 696));

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 0, -1, 696));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCategoryNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemCategoryNameFocusGained
        
        itemCategoryName.setText("");
        
    }//GEN-LAST:event_itemCategoryNameFocusGained

    private void itemCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoryNameActionPerformed
      
    }//GEN-LAST:event_itemCategoryNameActionPerformed

    private void itemBatchIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemBatchIdFocusGained
         
        if(!isLoaded)
        itemBatchId.setText(null);
        else{
            itemBatchId.setText(String.valueOf(batch_id));
        }
    }//GEN-LAST:event_itemBatchIdFocusGained

    private void itemBatchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBatchIdActionPerformed
       
    }//GEN-LAST:event_itemBatchIdActionPerformed

    private void thogaPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_thogaPriceFocusGained
         thogaPrice.setText(null);
    }//GEN-LAST:event_thogaPriceFocusGained

    private void thogaPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thogaPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thogaPriceActionPerformed

    private void itemQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemQuantityFocusGained
        itemQuantity.setText(null);
    }//GEN-LAST:event_itemQuantityFocusGained

    private void itemQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQuantityActionPerformed

    private void enter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_btnActionPerformed
         try {
            String id = itemId.getText();
            long item_id=Long.parseLong(id);
            String category_name=itemCategoryName.getText();
            
//            int category_id=category.getCategory(category_name).getC_id();
//             System.out.println("jfldsjlkfas"+category_id);
            double thoga_price=Double.parseDouble(thogaPrice.getText());
            double quantity=Integer.parseInt(itemQuantity.getText());
            double item_price=Double.parseDouble(itemTakingPrice.getText());
            int batch_id=Integer.parseInt(itemBatchId.getText());
            double taking_price=Double.parseDouble(itemTakingPrice.getText());
            double our_price=Double.parseDouble(ourPrice.getText());
            double show_price=Double.parseDouble(txtShowPrice.getText());
            String item_description=description.getText();
            int warning=Integer.parseInt(warningLevel.getText());
//             System.out.println("jflkdsjf"+item_id);
            boolean isAdded = controller.addItem(item_id,thoga_price,quantity,item_price,batch_id,taking_price,our_price,item_description,Integer.parseInt(category_name),warning,show_price);
            if(isAdded)
            this.dispose();
            else{
                JOptionPane.showMessageDialog(this,"Added Failed", "Something went wrong", JOptionPane.ERROR_MESSAGE);
                itemCategoryName.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(AddSupplierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enter_btnActionPerformed

    private void itemTakingPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemTakingPriceFocusGained
       itemTakingPrice.setText(null);
    }//GEN-LAST:event_itemTakingPriceFocusGained

    private void itemTakingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTakingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTakingPriceActionPerformed

    private void itemIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemIdFocusGained
        itemId.setText(null);
    }//GEN-LAST:event_itemIdFocusGained

    private void itemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdActionPerformed
      try {
          List<Item> all = controller.getAll();
          for (Item item : all) {
              if(!itemId.getText().equals("")){
              if(Long.parseLong(itemId.getText())==item.getI_id()){
                  JOptionPane.showMessageDialog(this, "Already in items","Warning",JOptionPane.WARNING_MESSAGE);
                  isAvailable=true;
                  itemId.setText("");
                  itemId.requestFocus();
              }
              }
          }
      } catch (SQLException ex) {
          Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_itemIdActionPerformed

    private void select_batchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_batchIdActionPerformed
//       this.dispose();
       new GetCategoryDetails(this).setVisible(true);
    }//GEN-LAST:event_select_batchIdActionPerformed

    private void ourPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ourPriceFocusGained
        ourPrice.setText(null);
    }//GEN-LAST:event_ourPriceFocusGained

    private void ourPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ourPriceActionPerformed

    private void warningLevelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_warningLevelFocusGained
        warningLevel.setText(null);
    }//GEN-LAST:event_warningLevelFocusGained

    private void warningLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warningLevelActionPerformed

    private void txtShowPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtShowPriceFocusGained
        txtShowPrice.setText("");
    }//GEN-LAST:event_txtShowPriceFocusGained

    private void txtShowPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowPriceActionPerformed

    private void select_batchId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_batchId1ActionPerformed
        new GetBatchDetails(this).setVisible(true);
    }//GEN-LAST:event_select_batchId1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");    
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JButton enter_btn;
    private javax.swing.JTextField itemBatchId;
    private javax.swing.JTextField itemCategoryName;
    private javax.swing.JTextField itemId;
    private javax.swing.JTextField itemQuantity;
    private javax.swing.JTextField itemTakingPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ourPrice;
    private javax.swing.JButton select_batchId;
    private javax.swing.JButton select_batchId1;
    private javax.swing.JSeparator sepFour1;
    private javax.swing.JSeparator sepFour10;
    private javax.swing.JSeparator sepFour2;
    private javax.swing.JSeparator sepFour3;
    private javax.swing.JSeparator sepFour4;
    private javax.swing.JSeparator sepFour5;
    private javax.swing.JSeparator sepFour6;
    private javax.swing.JSeparator sepFour7;
    private javax.swing.JSeparator sepFour8;
    private javax.swing.JSeparator sepFour9;
    private javax.swing.JTextField thogaPrice;
    private javax.swing.JTextField txtShowPrice;
    private javax.swing.JTextField warningLevel;
    // End of variables declaration//GEN-END:variables
}
