/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CategoryController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Batch;
import model.Category;

/**
 *
 * @author kasun
 */
public class GetCategoryDetails extends javax.swing.JFrame {
    private AddItemForm form;
    private UpdateItemForm updateForm;
    private CategoryController controller=new CategoryController();
    /**
     * Creates new form GetCategoryDetails
     */
    public GetCategoryDetails() {
        initComponents();
        this.setLocationRelativeTo(null);
//        this.setSize(1051,657);
        loadData();
    }
    public GetCategoryDetails(AddItemForm form){
        this.form=form;
          initComponents();
        this.setLocationRelativeTo(null);
//        this.setSize(1051,657);
                loadData();
    }
    
    public GetCategoryDetails(UpdateItemForm updateForm){
        this.updateForm=updateForm;
         initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1051,657);
                loadData();
    }
    private void loadData(){
        try {
            DefaultTableModel default_table=(DefaultTableModel)batchDetails.getModel();
            List<Category> list=new ArrayList<>();
            list=controller.getAll();
            if(!list.isEmpty()){
                for(Category batch:list){
                    default_table.addRow(new Object[]{batch.getC_id(),batch.getName()});
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Empty Records");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GetCategoryDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        batchDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Category");

        pnlBase.setBackground(new java.awt.Color(153, 0, 153));
        pnlBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batchDetails.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        batchDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(batchDetails);

        pnlBase.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 700, 450));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Category Details");
        pnlBase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 450, 80));

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton1.setText("Select");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlBase.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int row=batchDetails.getSelectedRow();
        int count=batchDetails.getSelectedRowCount();
        if(count==0)JOptionPane.showMessageDialog(this, "enter only one row", "warning", JOptionPane.WARNING_MESSAGE);
        else if(count>1)JOptionPane.showMessageDialog(this, "enter only one row", "warning", JOptionPane.WARNING_MESSAGE);
        else{
        int column=0;
        String data=batchDetails.getModel().getValueAt(row, column).toString();
        int batch_id=Integer.parseInt(data);
        this.dispose();
        if(updateForm!=null)updateForm.setCategoryId(data);
        if(form!=null)form.setCategoryId(data);
        this.dispose();
        }
        //        new AddItemForm(batch_id).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetCategoryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetCategoryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetCategoryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetCategoryDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetCategoryDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable batchDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBase;
    // End of variables declaration//GEN-END:variables
}
