/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BatchController;
import controller.SupplierController;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Batch;
import model.Supplier;

/**
 *
 * @author kasun
 */
public class ViewBatchForm extends javax.swing.JFrame {
    private SupplierController supController;
    private BatchController batController;
    /**
     * Creates new form ViewBatchForm
     */
    public ViewBatchForm() {
        supController=new SupplierController();
        batController=new BatchController();
        initComponents();
        this.setSize(1152,619);
        this.setLocationRelativeTo(null);
        
        loadTable();
    }
    
    private void loadTable(){
        try {
            DefaultTableModel dtm=(DefaultTableModel) tblBatch.getModel();
            List<Batch> all = batController.getAll();
            for (Batch batch : all) {
                Object [] row={batch.getB_id(),supController.getSupplierByID(batch.getS_id()).getName(),batch.getTime()};
                dtm.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewBatchForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        lblDelete = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBatch = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(153, 0, 153));
        pnlBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDelete.setBackground(new java.awt.Color(51, 0, 255));
        lblDelete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblDelete.setForeground(new java.awt.Color(255, 255, 255));
        lblDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelete.setText("Delete");
        lblDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDelete.setOpaque(true);
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });
        pnlBase.add(lblDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, 70, 30));

        lblUpdate.setBackground(new java.awt.Color(51, 0, 255));
        lblUpdate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdate.setText("Update");
        lblUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblUpdate.setOpaque(true);
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
        });
        pnlBase.add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, 70, 30));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Batch Details");
        pnlBase.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 410, 110));

        tblBatch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblBatch.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tblBatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch ID", "Supplier Name", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBatch);

        pnlBase.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 889, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) tblBatch.getModel();
        if(tblBatch.getSelectedRowCount()>0){
            JOptionPane.showMessageDialog(this, "select only one row at time", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(tblBatch.getSelectedRowCount()==0)
        JOptionPane.showMessageDialog(this, "select one row at time", "Warning", JOptionPane.WARNING_MESSAGE);
        else{
            int  id = (int) dtm.getValueAt(tblBatch.getSelectedRow(), 0);
            String name =  (String) dtm.getValueAt(tblBatch.getSelectedRow(), 1);
            Timestamp date= (Timestamp) dtm.getValueAt(tblBatch.getSelectedRow(), 2);
            Batch sup=new Batch();
            sup.setB_id(id);
            sup.setTime(date);
            JFrame frame= new DeleteBatchForm(sup,name);
            frame.setVisible(true);
        }
        loadTable();

    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        DefaultTableModel dtm=(DefaultTableModel) tblBatch.getModel();
        if(tblBatch.getSelectedRowCount()>0){
            JOptionPane.showMessageDialog(this, "select only one row at time", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(tblBatch.getSelectedRowCount()==0)
        JOptionPane.showMessageDialog(this, "select one row at time", "Warning", JOptionPane.WARNING_MESSAGE);
        else{

            int  id = (int) dtm.getValueAt(tblBatch.getSelectedRow(), 0);
            String name =  (String) dtm.getValueAt(tblBatch.getSelectedRow(), 1);
            Timestamp date= (Timestamp) dtm.getValueAt(tblBatch.getSelectedRow(), 2);
            Batch sup=new Batch();
            sup.setB_id(id);
            sup.setTime(date);
            JFrame frame= new UpdateBatchForm(sup,name);
            frame.setVisible(true);
        }
        loadTable();

    }//GEN-LAST:event_lblUpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBatchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBatchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JTable tblBatch;
    // End of variables declaration//GEN-END:variables
}
